/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module \$paramod\adder\WIDTH=s32'00000000000000000000000000010000 (a, b, sum, carry);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output carry;
  wire carry;
  wire [16:0] full_sum;
  output [15:0] sum;
  wire [15:0] sum;
  assign full_sum = { 1'h0, a } + { 1'h0, b };
  assign carry = full_sum[16];
  assign sum = full_sum[15:0];
endmodule

module \$paramod\logic_unit\WIDTH=s32'00000000000000000000000000010000 (a, b, opcode, result);
  wire [15:0] _00_;
  wire [15:0] _01_;
  wire [15:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [15:0] _07_;
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [15:0] result;
  wire [15:0] result;
  assign _00_ = a & b;
  assign _01_ = ~ a;
  assign _02_ = a | b;
  function [15:0] _11_;
    input [15:0] a;
    input [63:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _11_ = b[15:0];
      4'b??1?:
        _11_ = b[31:16];
      4'b?1??:
        _11_ = b[47:32];
      4'b1???:
        _11_ = b[63:48];
      default:
        _11_ = a;
    endcase
  endfunction
  assign result = _11_(16'h0000, { _00_, _02_, _07_, _01_ }, { _06_, _05_, _04_, _03_ });
  assign _03_ = opcode == 3'h7;
  assign _04_ = opcode == 3'h6;
  assign _05_ = opcode == 3'h5;
  assign _06_ = opcode == 3'h4;
  assign _07_ = a ^ b;
endmodule

module \$paramod\multiplier\WIDTH=s32'00000000000000000000000000010000 (a, b, product);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output [31:0] product;
  wire [31:0] product;
  assign product = a * b;
endmodule

module \$paramod\operand_isolation\WIDTH=s32'00000000000000000000000000010000 (a, b, add_en, sub_en, mul_en, logic_en, add_a, add_b, sub_a, sub_b, mul_a, mul_b, logic_a, logic_b);
  input [15:0] a;
  wire [15:0] a;
  output [15:0] add_a;
  wire [15:0] add_a;
  output [15:0] add_b;
  wire [15:0] add_b;
  input add_en;
  wire add_en;
  input [15:0] b;
  wire [15:0] b;
  output [15:0] logic_a;
  wire [15:0] logic_a;
  output [15:0] logic_b;
  wire [15:0] logic_b;
  input logic_en;
  wire logic_en;
  output [15:0] mul_a;
  wire [15:0] mul_a;
  output [15:0] mul_b;
  wire [15:0] mul_b;
  input mul_en;
  wire mul_en;
  output [15:0] sub_a;
  wire [15:0] sub_a;
  output [15:0] sub_b;
  wire [15:0] sub_b;
  input sub_en;
  wire sub_en;
  assign add_a = add_en ? a : 16'h0000;
  assign add_b = add_en ? b : 16'h0000;
  assign sub_a = sub_en ? a : 16'h0000;
  assign sub_b = sub_en ? b : 16'h0000;
  assign mul_a = mul_en ? a : 16'h0000;
  assign mul_b = mul_en ? b : 16'h0000;
  assign logic_a = logic_en ? a : 16'h0000;
  assign logic_b = logic_en ? b : 16'h0000;
endmodule

module \$paramod\subtractor\WIDTH=s32'00000000000000000000000000010000 (a, b, diff, borrow);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  output borrow;
  wire borrow;
  output [15:0] diff;
  wire [15:0] diff;
  assign borrow = a < b;
  assign diff = a - b;
endmodule

module low_power_apu(clk, rst, enable, opcode, A, B, result, flags, valid);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  input [15:0] A;
  wire [15:0] A;
  input [15:0] B;
  wire [15:0] B;
  wire [15:0] add_a;
  wire [15:0] add_b;
  wire add_carry;
  wire add_en;
  wire [15:0] add_result;
  input clk;
  wire clk;
  input enable;
  wire enable;
  output [6:0] flags;
  wire [6:0] flags;
  wire [15:0] logic_a;
  wire [15:0] logic_b;
  wire logic_en;
  wire [15:0] logic_result;
  wire [15:0] mul_a;
  wire [15:0] mul_b;
  wire mul_en;
  wire [31:0] mul_result;
  wire [6:0] next_flags;
  wire [31:0] next_result;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [31:0] result;
  reg [31:0] result;
  input rst;
  wire rst;
  wire [15:0] sub_a;
  wire [15:0] sub_b;
  wire sub_borrow;
  wire sub_en;
  wire [15:0] sub_result;
  output valid;
  reg valid;
  assign _00_ = _16_ & _28_;
  assign _01_ = _27_ & _29_;
  always @(posedge clk)
    if (rst) result <= 32'd0;
    else if (enable) result <= next_result;
  always @(posedge clk)
    if (rst) valid <= 1'h0;
    else valid <= _22_;
  reg [5:0] _34_;
  always @(posedge clk)
    if (rst) _34_ <= 6'h00;
    else if (enable) _34_ <= next_flags[5:0];
  assign flags[5:0] = _34_;
  assign _02_ = ! add_result;
  assign _03_ = ! sub_result;
  assign _04_ = ! mul_result;
  assign _05_ = ! logic_result;
  assign add_en = enable && _06_;
  assign sub_en = enable && _07_;
  assign mul_en = enable && _08_;
  assign logic_en = enable && _15_;
  assign _13_ = _09_ || _10_;
  assign _14_ = _13_ || _11_;
  assign _15_ = _14_ || _12_;
  assign _16_ = ~ _27_;
  assign _17_ = ~ _23_;
  assign _18_ = ~ _24_;
  assign _19_ = ~ _25_;
  assign _20_ = ~ _26_;
  assign next_flags[3] = _07_ ? sub_borrow : 1'h0;
  assign next_flags[2] = _06_ ? add_carry : 1'h0;
  function [0:0] _53_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _53_ = b[0:0];
      4'b??1?:
        _53_ = b[1:1];
      4'b?1??:
        _53_ = b[2:2];
      4'b1???:
        _53_ = b[3:3];
      default:
        _53_ = a;
    endcase
  endfunction
  assign next_flags[1] = _53_(1'h0, { add_result[15], sub_result[15], mul_result[31], logic_result[15] }, { _06_, _07_, _08_, _21_ });
  assign _21_ = | { _12_, _11_, _10_, _09_ };
  function [0:0] _55_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _55_ = b[0:0];
      4'b??1?:
        _55_ = b[1:1];
      4'b?1??:
        _55_ = b[2:2];
      4'b1???:
        _55_ = b[3:3];
      default:
        _55_ = a;
    endcase
  endfunction
  assign next_flags[0] = _55_(1'h0, { _02_, _03_, _04_, _05_ }, { _06_, _07_, _08_, _21_ });
  function [0:0] _56_;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _56_ = b[0:0];
      4'b??1?:
        _56_ = b[1:1];
      4'b?1??:
        _56_ = b[2:2];
      4'b1???:
        _56_ = b[3:3];
      default:
        _56_ = a;
    endcase
  endfunction
  assign next_flags[5] = _56_(1'h0, { _17_, _18_, _19_, _20_ }, { _06_, _07_, _08_, _21_ });
  function [31:0] _57_;
    input [31:0] a;
    input [127:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _57_ = b[31:0];
      4'b??1?:
        _57_ = b[63:32];
      4'b?1??:
        _57_ = b[95:64];
      4'b1???:
        _57_ = b[127:96];
      default:
        _57_ = a;
    endcase
  endfunction
  assign next_result = _57_(32'd0, { 16'h0000, add_result, 16'h0000, sub_result, mul_result, 16'h0000, logic_result }, { _06_, _07_, _08_, _21_ });
  assign _09_ = opcode == 3'h4;
  assign _10_ = opcode == 3'h5;
  assign _11_ = opcode == 3'h6;
  assign _12_ = opcode == 3'h7;
  assign _08_ = opcode == 3'h2;
  assign _07_ = opcode == 3'h1;
  assign _06_ = ! opcode;
  assign _22_ = enable ? 1'h1 : 1'h0;
  function [0:0] _66_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _66_ = b[0:0];
      2'b1?:
        _66_ = b[1:1];
      default:
        _66_ = a;
    endcase
  endfunction
  assign next_flags[4] = _66_(1'h0, { _00_, _01_ }, { _06_, _07_ });
  assign _23_ = ^ add_result;
  assign _24_ = ^ sub_result;
  assign _25_ = ^ mul_result;
  assign _26_ = ^ logic_result;
  assign _28_ = add_result[15] ^ A[15];
  assign _27_ = A[15] ^ B[15];
  assign _29_ = sub_result[15] ^ A[15];
  \$paramod\adder\WIDTH=s32'00000000000000000000000000010000  u_adder (
    .a(add_a),
    .b(add_b),
    .carry(add_carry),
    .sum(add_result)
  );
  \$paramod\logic_unit\WIDTH=s32'00000000000000000000000000010000  u_logic_unit (
    .a(logic_a),
    .b(logic_b),
    .opcode(opcode),
    .result(logic_result)
  );
  \$paramod\multiplier\WIDTH=s32'00000000000000000000000000010000  u_multiplier (
    .a(mul_a),
    .b(mul_b),
    .product(mul_result)
  );
  \$paramod\operand_isolation\WIDTH=s32'00000000000000000000000000010000  u_operand_isolation (
    .a(A),
    .add_a(add_a),
    .add_b(add_b),
    .add_en(add_en),
    .b(B),
    .logic_a(logic_a),
    .logic_b(logic_b),
    .logic_en(logic_en),
    .mul_a(mul_a),
    .mul_b(mul_b),
    .mul_en(mul_en),
    .sub_a(sub_a),
    .sub_b(sub_b),
    .sub_en(sub_en)
  );
  \$paramod\subtractor\WIDTH=s32'00000000000000000000000000010000  u_subtractor (
    .a(sub_a),
    .b(sub_b),
    .borrow(sub_borrow),
    .diff(sub_result)
  );
  assign flags[6] = 1'h0;
  assign next_flags[6] = 1'h0;
endmodule
